services:
  backend:
    image: clicker-backend:latest
    container_name: clicker-backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
  frontend:
    image: clicker-frontend:latest
    container_name: clicker-frontend
    build:
      context: ./frontend
      args:
        VITE_SECRET_SALT: ${VITE_SECRET_SALT:-pixel_city_sauvegarde_secrete_local}
    ports:
      - "8080:80"
    depends_on:
      - backend
  redis:
    image: redis:alpine
    container_name: clicker-redis

# docker-compose up -d --build
# docker-compose down
